name: Deploy Java App to UAT VM

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Maven Project
        shell: powershell
        run: |
          & "C:\Program Files\Apache\Maven\apache-maven-3.9.14\bin\mvn.cmd" clean package -DskipTests

      - name: Build Docker Image
        shell: powershell
        run: docker build -t boardgame-app .

      - name: Stop Old Container
        shell: powershell
        run: docker stop boardgame-app

      - name: Remove Old Container
        shell: powershell
        run: docker rm boardgame-app

      - name: Run Docker Container
        shell: powershell
        run: docker run -d -p 8080:8080 --name boardgame-app boardgame-app
