name: Deploy Java App to UAT VM

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Maven Project
        run:  mvn.cmd clean package -DskipTests

      - name: Build Docker Image
        run: docker build -t boardgame-app .

      - name: Stop Old Container
        run: docker stop boardgame-app || true

      - name: Remove Old Container
        run: docker rm boardgame-app || true

      - name: Run Docker Container
        run: docker run -d -p 8080:8080 --name boardgame-app boardgame-app
