name: Build and Deploy Java App

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Build with Maven
      run: mvn clean package -DskipTests

    - name: Stop existing app (if running)
      run: |
        pkill -f 'java -jar' || true

    - name: Run Application
      run: |
        nohup java -jar target/*.jar > app.log 2>&1 &
